import { library } from "@fortawesome/fontawesome-svg-core";
import { faGithub } from "@fortawesome/free-brands-svg-icons";
import {
  faShuffle,
  faTrash,
  faMoon,
  faHouse,
  faUndo,
  faRedo,
  faDice,
  faList,
  faPlus,
  faMinus,
  faCircleCheck,
  faThumbsDown,
  faLocationDot,
  faLocationCrosshairs,
  faFlag,
  faDownLong,
  faSearch,
  faXmark,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faTableList,
  faQrcode,
  faMagicWandSparkles,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faShuffle,
  faTrash,
  faMoon,
  faHouse,
  faUndo,
  faRedo,
  faDice,
  faList,
  faPlus,
  faMinus,
  faCircleCheck,
  faThumbsDown,
  faLocationDot,
  faLocationCrosshairs,
  faFlag,
  faDownLong,
  faGithub,
  faSearch,
  faXmark,
  faChevronLeft,
  faChevronRight,
  faCircle,
  faTableList,
  faQrcode,
  faMagicWandSparkles,
);

export default {};
